import leaf from './src/assets/leaf.png';
import movieic from './src/assets/moviesic.png';
import musicclef from './src/assets/musicclef.png';
import picture from './src/assets/picture.png';
import playlist from './src/assets/playlist.png';
import rightarrow from './src/assets/Rarrow.png';
import videofile from './src/assets/videofile.png';
import voiceid from './src/assets/voiceid.png';
import videoplay from './src/assets/videoplay.png';
import camerastudio from './src/assets/camerastudio.png';
import microphone from './src/assets/microphone.png';
import videoslider from './src/assets/videoslider.png';

const locationPins = [
  {
    id: 1,
    locationName: "Ota 42 - Adum",
    importance: "KO-JO'S BIRTHPLACE AND MOTHER'S FAMILY HOME",
    coords: { top: "13%", left: "19.5%" },
    image: "",
    songTitle: "Fruit of the Womb",
    songUrl: "",
    videoUrl: "",
    artistName: "Kojo Cue",
    lyrics: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laudantium, ad ab provident at commodi corporis perferendis perspiciatis nulla velit accusantium quas aliquid doloremque quasi! Nesciunt ex ipsam id est? Illum nulla sunt voluptas necessitatibus dicta accusantium doloremque repellat atque, dolore incidunt laborum placeat adipisci earum suscipit aliquam nam quo debitis autem architecto, libero sapiente esse consequatur! Odit, animi harum eligendi, doloremque commodi eaque perferendis ut, enim aperiam corrupti repellat. Quia dolor aliquid voluptatibus soluta odio cumque explicabo odit, perspiciatis omnis. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laudantium, ad ab provident at commodi corporis perferendis perspiciatis nulla velit accusantium quas aliquid doloremque quasi! Nesciunt ex ipsam id est? Illum nulla sunt voluptas necessitatibus dicta accusantium doloremque repellat atque, dolore incidunt laborum placeat adipisci earum suscipit aliquam nam quo debitis autem architecto, libero sapiente esse consequatur! Odit, animi harum eligendi, doloremque commodi eaque perferendis ut, enim aperiam corrupti repellat. Quia dolor aliquid voluptatibus soluta odio cumque explicabo odit, perspiciatis omnis",
    buttons: [
      { text: "FILM REEL", style: "border-2 border-[#a8743b] text-[#7B3F00]  rock w-full h-[49px] mt-2 tracking-wide",  iconSize: "w-[32px] h-[32px]", icon: movieic, iconColor: "#7B3F00", arrow: rightarrow, arrowColor: "#7B3F00", link: "" },
      { text: "REFLECTIONS", style: "bg-[#B69F7C]  border-2 border-[#a8743b] rock  w-full h-[49px] mt-2 text-[#E1DDD4]",  iconSize: "w-[32] h-[32px]",  icon:leaf, arrow:rightarrow,  link: "" },
      { text: "LYRICS", style: "border-2 border-[#B69F7C] text-[#7B3F00] bg-transparent rock  w-full h-[49px] mt-2 text-[#7B3F00]",iconSize: "w-[32px] h-[32px]", icon: musicclef,  arrow: rightarrow,link: "" },
    ],
    prevButton: { text: 'Previous', link: '' },
    nextButton: { text: 'Next Location', arrow: rightarrow, link: '' },
  },
  {
    id: 2,
    locationName: "Ota 42 - Adum",
    importance: "KO-JO'S BIRTHPLACE AND MOTHER'S FAMILY HOME",
    image: "",
    coords: { top: "5%", left: "68%" },
    songTitle: "Big Boy",
    songUrl: "",
    videoUrl: "",
    artistName: "Kojo Cue",
    lyrics: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laudantium, ad ab provident at commodi corporis perferendis perspiciatis nulla velit accusantium quas aliquid doloremque quasi! Nesciunt ex ipsam id est? Illum nulla sunt voluptas necessitatibus dicta accusantium doloremque repellat atque, dolore incidunt laborum placeat adipisci earum suscipit aliquam nam quo debitis autem architecto, libero sapiente esse consequatur! Odit, animi harum eligendi, doloremque commodi eaque perferendis ut, enim aperiam corrupti repellat. Quia dolor aliquid voluptatibus soluta odio cumque explicabo odit, perspiciatis omnis",
    buttons: [
      { text: "FILM REEL", style: "text-[#7B3F00] border-2  border-[#B69F7C] rock text-[#7B3F00] w-full h-[49px] mt-[6rem]", iconSize: "w-[32px] h-[32px]", icon: movieic, arrow: rightarrow, link: "" },
      { text: "REFLECTIONS", style: "rock border-2 border-[#B69F7C] text-[#E1DDD4] bg-[#B69F7C] w-full h-[49px]",  iconSize: "w-[32px] h-[32px]", icon: leaf, arrow: rightarrow, arrowColor: "#E1DDD4", link: "" },
    ],
    prevButton: { text: 'Previous', link: '' },
    nextButton: { text: 'Next Location', arrow: rightarrow, link: '' },

  },
  {
    id: 3,
    locationName: "Kotoko - Oduom",
    importance: "First friendship, first injury, love for football",
    image: "",
    coords: { top: "32%", left: "50%" },
    songTitle: "Next term",
    songUrl: "",
    videoUrl: "",
    artistName: "Kojo Cue",
    lyrics: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laudantium, ad ab provident at commodi corporis perferendis perspiciatis nulla velit accusantium quas aliquid doloremque quasi! Nesciunt ex ipsam id est? Illum nulla sunt voluptas necessitatibus dicta accusantium doloremque repellat atque, dolore incidunt laborum placeat adipisci earum suscipit aliquam nam quo debitis autem architecto, libero sapiente esse consequatur! Odit, animi harum eligendi, doloremque commodi eaque perferendis ut, enim aperiam corrupti repellat. Quia dolor aliquid voluptatibus soluta odio cumque explicabo odit, perspiciatis omnis",
    buttons: [
      { text: "MIXING NOTES", style: "border-2 border-[#B69F7C] text-[#7B3F00]  mt-[rem] bg-transparent rock w-full h-[49px] mt-[1.5rem]",  iconSize:"w-[32px] h-[32px]", icon: videofile,  arrow: rightarrow, arrowColor: "#7B3F00", link: "" },
      { text: "VOICE NOTE", style: "bg-[#B69F7C] text-[#E1DDD4] border-2 border-[#B69F7C] rock w-full h-[49px]", iconSize: "w-[32px] h-[32px]",  icon: voiceid,arrow: rightarrow, link: "" },
      { text: "LYRICS BREAKDOWN", style: "border-2 border-[#B69F7C] text-[#7B3F00] bg-transparent rock w-full   h-[49px]", iconSize: "w-[32px] h-[32px]", icon: playlist, arrow: rightarrow, link: "" },
    ],
    prevButton: { text: 'Previous', link: '' },
    nextButton: { text: 'Next Location', arrow: rightarrow, link: '' },
  },
  {
    id: 4,
    locationName: "Jamaica House - Bantama",
    importance: "Core childhood home. Father’s side of the family",
    image: "",
    coords: { top: "23%", left: "77.8%" },
    songTitle: "Bantama Blues 3",
    songUrl: "",
    videoUrl: "",
    artistName: "Kojo Cue",
    lyrics: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laudantium, ad ab provident at commodi corporis perferendis perspiciatis nulla velit accusantium quas aliquid doloremque quasi! Nesciunt ex ipsam id est? Illum nulla sunt voluptas necessitatibus dicta accusantium doloremque repellat atque, dolore incidunt laborum placeat adipisci earum suscipit aliquam nam quo debitis autem architecto, libero sapiente esse consequatur! Odit, animi harum eligendi, doloremque commodi eaque perferendis ut, enim aperiam corrupti repellat. Quia dolor aliquid voluptatibus soluta odio cumque explicabo odit, perspiciatis omnis",
    buttons: [
      { text: "BTS PHOTOS", style: "border-2 border-[#B69F7C] text-[#B69F7C] rock w-full h-[49px] mt-[1.2rem] ", iconSize: "w-[32px] h-[32px]", icon: picture,  arrow: rightarrow, link: "" },
      { text: "LYRICS BREAKDOWN", style: "text-[#7B3F00] border-2 border-[#B69F7C] rock w-full h-[49px]", iconSize:"w-[32px] h-[32]", icon: playlist,  arrow: rightarrow,  link: "" },
      { text: "WATCH MUSIC VIDEO", style: "text-[#E1DDD4] bg-[#B69F7C] rock", iconSize: "w-[32px] h-[32px]",  icon: videoslider,arrow: rightarrow,  link: "" },
    ],
    prevButton: { text: 'Previous', link: '' },
    nextButton: { text: 'Next Location', arrow: rightarrow, link: '' },
  },
  {
    id: 5,
    locationName: "Jamaica House - Bantama",
    importance: "Core childhood home. Father’s side of the family",
    image: "",
    coords: { top: "55%", left: "45.8%" },
    songTitle: "Abrantie",
    songUrl: "",
    videoUrl: "",
    artistName: "Kojo Cue",
    buttons: [
      { text: "FILM REEL", style: "border-2 border-[#B69F7C] text-[#7B3F00] rock w-full h-[49px] mt-[6.4rem]", iconSize: "w-[32px] h-[32px]", icon: movieic,  arrow: rightarrow,  link: "" },
      { text: "Lyrics Breakdown", style: "border-2 border-[#B69F7C] text-[#7B3F00] rock w-full h-[49px]",  iconSize: "w-[32px] h-[32px]", icon: playlist,  arrow: rightarrow, link: "" },
    ],
    prevButton: { text: 'Previous', link: '' },
    nextButton: { text: 'Next Location', arrow: rightarrow, link: '' },
  },
  {
    id: 6,
    locationName: "OWASS BASIC - Santasi",
    importance: "Junior and senior school years; early rap influences.",
    image: "",
    coords: { top: "57%", left: "42%" },
    songTitle: "Squad",
    songUrl: "",
    videoUrl: "",
    artistName: "Kojo Cue",
    buttons: [
      { text: "VISUALIZER", style: "border-2 border-[#B69F7C] text-[#7B3F00] rock w-full h-[49px mt-[5.7rem]",iconSize: "w-[32px] h-[32px]",  icon: videoplay, iconColor: "#7B3F00", arrow: rightarrow, arrowColor: "#7B3F00", link: "" },
      { text: "LYRICS BREAKDOWN", style: "border-2 border-[#B69F7C] text-[#a8743b] rock w-full h-[49px]", iconSize: "w-[32px] h-[32px]", icon: playlist,  arrow: rightarrow, link: "" },
    ],
    prevButton: { text: 'Previous', link: '' },
    nextButton: { text: 'Next Location', arrow: rightarrow, link: '' },
  },
  {
    id: 7,
    locationName: "OWASS BASIC - Santasi",
    importance: "Junior and senior school years; early rap influences.",
    image: "",
    coords: { top: "69.8%", left: "27.2%" },
    songTitle: "Mr. Eben Interlude",
    songUrl: "",
    videoUrl: "",
    artistName: "Kojo Cue",
    buttons: [
      { text: "LYRICS BREAKDOWN", style: "border-2 border-[#B69F7C] text-[#7B3F00] rock w-full h-[49px] mt-[1.6rem]", iconSize: "w-5 h-5",  icon: playlist,  arrow: rightarrow, iconSize: "w-[32px] h-[32px]", link: "" },
      { text: "INTERVIEW", style: "text-[#7B3F00] border-2 border-[#B69F7C] rock w-full h-[49px]",  iconSize: "w-[32px] h-[32px]", icon: microphone,  arrow: rightarrow,  link: "" },
      { text: "MIXING NOTES", style: "border-2 border-[#B69F7C] text-[#7B3F00] rock w-full h-[49px]", iconSize: "w-[32px] h-[32px]", icon: videofile,  arrow: rightarrow,  link: "" },
    ],
    prevButton: { text: 'Previous', link: '' },
    nextButton: { text: 'Next Location', arrow: rightarrow, link: '' },
  },
  {
    id: 8,
    locationName: "SMALL LONDON - Breman",
    importance: "Grandmother's death and family changes.",
    image: "",
    coords: { top: "81.7%", left: "47.8%" },
    songTitle: "Mysterious Ways",
    songUrl: "",
    videoUrl: "",
    artistName: "Kojo Cue",
    buttons: [
      { text: "FULL LYRICS", style: "border-2 border-[#B69F7C] text-[#7B3F00] rock w-full h-[49px] mt-[6.2rem]", iconSize: "w-[32px] h-[32px]", icon: musicclef, iconColor: "#7B3F00", arrow: rightarrow, arrowColor: "#7B3F00", link: "" },
      { text: "REFLECTION", style: "border-2 border-[#B69F7C] text-[#7B3F00] rock w-full h-[49px]",  iconSize: "w-[32px] h-[32px]",  icon: leaf, arrow: rightarrow, link: "" },
    ],
    prevButton: { text: 'Previous', link: '' },
    nextButton: { text: 'Next Location', arrow: rightarrow, link: '' }
  },
  {
    id: 9,
    locationName: "SMALL LONDON - Breman",
    importance: "Grandmother's death and family changes.",
    image: "",
    coords: { top: "88%", left: "56%" },
    songTitle: "Angel",
    songUrl: "",
    videoUrl: "",
    artistName: "Kojo Cue",
    buttons: [
      { text: "FILM REEL", style: "border-2 border-[#B69F7C] text-[#7B3F00] rock w-full h-[49px] mt-[1.5rem]",  iconSize: "w-[32px] h-[32px]",  icon: movieic,  arrow: rightarrow,  link: "" },
      { text: "MIXING NOTES", style: "text-[#7B3F00] border-2 border-[#B69F7C] rock w-full h-[49px]", iconSize: "w-[32px] h-[32px]", icon: videofile, arrow: rightarrow,  link: "" },
      { text: "VOICE NOTES", style: "border-2 border-[#B69F7C] text-[#7B3F00] bg-transparent rock w-full h-[49px]",  iconSize: "w-[32px] h-[32px]", icon: voiceid,  arrow: rightarrow,  link: "" },
    ],
    prevButton: { text: 'Previous', link: '' },
    nextButton: { text: 'Next Location', arrow: rightarrow, link: '' },
  },
  {
    id: 10,
    locationName: "F176 - Buokrom Estate",
    importance: "Adolescence, the first meeting with father.",
    image: "",
    coords: { top: "87%", left: "79%" },
    songTitle: "F176",
    songUrl: "",
    videoUrl: "",
    artistName: "Kojo Cue",
    buttons: [
      { text: "VOICE NOTE", style: "border-2 border-[#B69F7C] text-[#7B3F00] rock w-full h-[49px] mt-[10.8rem]",  iconSize: "w-[32px] h-[32px]",  icon: voiceid, arrow: rightarrow, link: "" },
    ],
    prevButton: { text: 'Previous', link: '' },
    nextButton: { text: 'Next Location', arrow: rightarrow, link: '' },
  },
  {
    id: 11,
    locationName: "F176 - Buokrom Estate",
    importance: "Adolescence, the first meeting with father.",
    image: "",
    coords: { top: "23%", left: "16%" },
    songTitle: "Grew Up Fast",
    songUrl: "",
    videoUrl: "",
    artistName: "Kojo Cue",
    buttons: [
      { text: "FULL LYRICS", style: "border-2 border-[#B69F7C] text-[#7B3F00] rock w-full h-[49px] mt-[10.8rem]",  iconSize: "w-[32px] h-[32px]",  icon: musicclef, arrow: rightarrow, link: "" },
    ],
    prevButton: { text: 'Previous', link: '' },
    nextButton: { text: 'Next Location', arrow: rightarrow, link: '' }
  },
  {
    id: 12,
    locationName: "F176 - Buokrom Estate",
    importance: "Adolescence, the first meeting with father.",
    image: "",
    coords: { top: "42%", left: "19.5%" },
    songTitle: "Tontonte",
    songUrl: "",
    videoUrl: "",
    artistName: "Kojo Cue",
    buttons: [
      { text: "BTS PHOTOS", style: "border-2 border-[#B69F7C] text-[#7B3F00] rock w-full h-[49px]  mt-[1.7rem]",  iconSize: "w-[32px] h-[32px]",  icon: picture,  arrow: rightarrow,  link: "/bts-photos/tontonte" },
      { text: "VISUALIZER", style: "text-[#7B3F00] border-2 border-[#B69F7C] rock w-full h-[49px]",  iconSize: "w-[32px] h-[32px]", icon: videoplay,arrow: rightarrow,  link: "" },
      { text: "FULL LYRICS", style: "border-2 border-[#B69F7C] text-[#7B3F00] rock w-full h-[49px]",  iconSize: "w-[32px] h-[32px]",  icon: musicclef, arrow: rightarrow,  link: "" },
    ],
    prevButton: { text: 'Previous', link: '' },
    nextButton: { text: 'Next Location', arrow: rightarrow, link: '' },
  },
  {
    id: 13,
    locationName: "CLAMP STREET - Lake",
    importance: "Current family home; recent life changes.",
    image: "",
    coords: { top: "13%", left: "43%" },
    songTitle: "Dreams",
    songUrl: "",
    videoUrl: "",
    artistName: "Kojo Cue",
    buttons: [
      { text: "FULL LYRICS", style: "border-2 border-[#B69F7C] text-[#7B3F00] rock w-full h-[49px] mt-[6.2rem]",  iconSize: "w-[32px] h-[32px]",  icon: musicclef,  arrow: rightarrow, link: "" },
      { text: "VOICE NOTE", style: "border-2 border-[#B69F7C] text-[#7B3F00] rock w-full h-[49px]",  iconSize: "w-[32px] h-[32px]",  icon: voiceid, arrow: rightarrow,  link: "" },
    ],
    prevButton: { text: 'Previous', link: '' },
    nextButton: { text: 'Next Location', arrow: rightarrow, link: '' },
  },
  {
    id: 14,
    locationName: "CLAMP STREET - Lake",
    importance: "Current family home; recent life changes.",
    image: "",
    coords: { top: "60%", left: "19.5%" },
    songTitle: "You Are",
    songUrl: "",
    videoUrl: "",
    artistName: "Kojo Cue",
    buttons: [
      { text: "FILM REEL", style: "border-2 border-[#B69F7C] text-[#7B3F00] rock mt-[0.4rem]", iconSize: "w-[32px] h-[32px]", icon: movieic,  arrow: rightarrow,  link: "/film-reel/you-are" },
      { text: "FULL LYRICS", style: "rock text-[#7B3F00] border-2 border-[#B69F7C]",  iconSize: "w-[32px] h-[32px]",  icon: musicclef, arrow: rightarrow, link: "" },
      { text: "BTS VIDEO", style: "border-2 border-[#B69F7C] text-[#7B3F00] rock w-full h-[49px]",  iconSize: "w-[32px] h-[32px]",  icon: camerastudio,  arrow: rightarrow, link: "" },
    ],
    prevButton: { text: 'Previous', link: '' },
    nextButton: { text: 'Next Location', arrow: rightarrow, link: '' },
  },
  {
    id: 15,
    locationName: "CLAMP STREET - Lake",
    importance: "Current family home; recent life changes.",
    image: "",
    coords: { top: "13%", left: "60%" },
    songTitle: "The Fall",
    songUrl: "",
    videoUrl: "",
    artistName: "Kojo Cue",
    buttons: [
      { text: "FILM REEL", style: "border-2 border-[#B69F7C] text-[#7B3F00] rock w-full h-[49px]  mt-[6.2rem]",  iconSize: "w-[32px] h-[32px]", icon: movieic, arrow: rightarrow,  link: "" },
      { text: "MIXING NOTES", style: "border-2 border-[#B69F7C] text-[#7B3F00] rock w-full h-[49px]",  iconSize: "w-[32px] h-[32px]",  icon: videofile,  arrow: rightarrow,  link: "" },
    ],
    prevButton: { text: 'Previous', link: '' },
    nextButton: { text: 'Next Location', arrow: rightarrow, link: '' },
  },
  {
    id: 16,
    locationName: "CLAMP STREET - Lake",
    importance: "Current family home; recent life changes.",
    image: "",
    coords: { top: "13%", left: "74%" },
    songTitle: "Onipa Hia Mmoa",
    songUrl: "",
    videoUrl: "",
    artistName: "Kojo Cue",
    buttons: [
      { text: "FULL LYRICS", style: "border-2 border-[#a8743b] text-[#a8743b] bg-transparent w-full h-[49px]  mt-[6.2rem]",  iconSize: "w-[32px] h-[32px]",  icon: musicclef, arrow: rightarrow,  link: "" },
      { text: "CUE LIVE SESSION", style: "border-2 border-[#a8743b] text-[#a8743b] bg-transparen w-full h-[49px]t",  iconSize: "w-[32px] h-[32px]",  icon: videoplay,  arrow: rightarrow, link: "" },
    ],
    prevButton: { text: 'Previous', link: '' },
    nextButton: { text: 'Next Location', arrow: rightarrow, link: '' },
  },
  {
    id: 17,
    locationName: "CLAMP STREET - Lake",
    importance: "Current family home; recent life changes.",
    image: "",
    coords: { top: "74%", left: "19.5%" },
    songTitle: "Onipa Hia Mmoa",
    songUrl: "",
    videoUrl: "",
    artistName: "Gold Dust",
    buttons: [
      { text: "WRITTEN STORY", style: "border-2 border-[#B69F7C] text-[#7B3F00] rock w-full h-[49px]  ", textSize: "text-sm md:text-base", iconSize: "w-[32px] h-[32px]",  icon: leaf,arrow: rightarrow,  link: "" },
      { text: "FULL LYRICS", style: "border-2 border-[#B69F7C] text-[#7B3F00] rock w-full h-[49px]",  iconSize: "w-[32px] h-[32px]", icon: musicclef,  arrow: rightarrow,  link: "" },
    ],
    prevButton: { text: 'Previous', link: '' },
    nextButton: { text: 'Next Location', arrow: rightarrow, link: '' },
  },
];

export default locationPins;